# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  # Image tag
  tag: '$(Build.BuildId)'

  # Docker repository
  repository: 'markoangelovski/dcc-scanner'

  # Build agent
  agent: 'Local builder'

stages:
- stage: BuildPush
  displayName: Build and push the image
  jobs:
  - job: Build
    displayName: Build the image job
    pool:
      name: $(agent)

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub service connection'
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Prod
  displayName: Release the image
  jobs:
  - job: Release
    displayName: Release the image job
    pool:
      name: $(agent)
    steps:
    - checkout: none
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Main service connection'
        appName: 'DCC-Scanner'
        containers: '$(repository):$(tag)'
        containerCommand: 'node app.js'